/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface ClassificationLog {
  category: string;
  confidence: number;
  created_at: Generated<string>;
  id: Generated<Int8>;
  inbox_message_id: number;
  json_parse_ok: boolean;
  latency_ms: number | null;
  model_version: string;
  raw_output: string | null;
  think_stripped: Generated<boolean>;
}

export interface DraftFeedback {
  draft_id: number;
  free_text: string | null;
  id: Generated<number>;
  operator_id: string | null;
  reason_code: string;
  rejected_at: Generated<string>;
}

export interface Drafts {
  approved_at: string | null;
  auto_send_blocked: Generated<boolean>;
  body_text: string | null;
  classification_category: string | null;
  classification_confidence: number | null;
  cost_usd: Numeric | null;
  created_at: Generated<string>;
  draft_body: string;
  draft_source: string | null;
  draft_subject: string | null;
  error_message: string | null;
  exemplar_refs: Generated<Json>;
  from_addr: string | null;
  id: Generated<number>;
  in_reply_to: string | null;
  inbox_message_id: number;
  input_tokens: number | null;
  kb_context_refs: Generated<Json>;
  last_retry_at: string | null;
  message_id: string | null;
  model: string;
  original_draft_body: string | null;
  output_tokens: number | null;
  rag_context_refs: Generated<Json>;
  rag_retrieval_reason: Generated<string>;
  received_at: string | null;
  references: string | null;
  sent_at: string | null;
  status: Generated<string>;
  subject: string | null;
  thread_id: string | null;
  to_addr: string | null;
  updated_at: Generated<string>;
}

export interface InboxMessages {
  body: string | null;
  classification: string | null;
  classified_at: string | null;
  confidence: Numeric | null;
  created_at: Generated<string | null>;
  draft_id: number | null;
  from_addr: string | null;
  id: Generated<number>;
  in_reply_to: string | null;
  message_id: string;
  model: string | null;
  received_at: string | null;
  references: string | null;
  snippet: string | null;
  subject: string | null;
  thread_id: string | null;
  to_addr: string | null;
}

export interface KbDocuments {
  chunk_count: Generated<number>;
  error_message: string | null;
  filename: string;
  id: Generated<number>;
  metadata: Generated<Json>;
  mime_type: string;
  processing_started_at: Generated<string>;
  ready_at: string | null;
  sha256: string;
  size_bytes: Int8;
  status: Generated<string>;
  title: string;
  uploaded_at: Generated<string>;
  uploaded_by: string | null;
}

export interface Migrations {
  applied_at: Generated<string>;
  version: string;
}

export interface Onboarding {
  admin_password_hash: string | null;
  admin_username: string | null;
  customer_key: Generated<string>;
  email_address: string | null;
  id: Generated<number>;
  ingest_progress_done: Generated<number>;
  ingest_progress_total: number | null;
  lived_at: string | null;
  stage: Generated<string>;
  started_at: Generated<string>;
  tuning_rated_count: Generated<number>;
  tuning_sample_count: Generated<number>;
}

export interface Persona {
  category_exemplars: Generated<Json>;
  created_at: Generated<string>;
  customer_key: Generated<string>;
  id: Generated<number>;
  last_refreshed_at: string | null;
  source_email_count: Generated<number>;
  statistical_markers: Generated<Json>;
  updated_at: Generated<string>;
}

export interface RejectedHistory {
  classification_category: string;
  classification_confidence: number;
  created_at: Generated<string>;
  draft_id: number;
  draft_original: string | null;
  from_addr: string;
  id: Generated<Int8>;
  inbox_message_id: number;
  rejected_at: Generated<string>;
  subject: string | null;
}

export interface SentHistory {
  body_text: string | null;
  classification_category: string;
  classification_confidence: number;
  created_at: Generated<string>;
  draft_id: number | null;
  draft_original: string | null;
  draft_sent: string;
  draft_source: string;
  exemplar_refs: Generated<Json>;
  from_addr: string;
  id: Generated<Int8>;
  inbox_message_id: number | null;
  kb_context_refs: Generated<Json>;
  message_id: string | null;
  rag_context_refs: Generated<Json>;
  rag_retrieval_reason: Generated<string>;
  sent_at: string;
  source: Generated<string>;
  subject: string | null;
  thread_id: string | null;
  to_addr: string;
}

export interface StateTransitions {
  actor: Generated<string>;
  draft_id: number;
  from_status: string;
  hash_chain: string | null;
  id: Generated<Int8>;
  reason: string | null;
  to_status: string;
  transitioned_at: Generated<string>;
}

export interface SystemState {
  bootstrap_complete: Generated<boolean>;
  bootstrap_messages_seen: Generated<number>;
  bootstrap_started_at: string | null;
  gmail_rate_limit_set_at: string | null;
  gmail_rate_limit_until: string | null;
  id: Generated<number>;
}

export interface VDraftingMetrics {
  classification_category: string | null;
  day: string | null;
  draft_source: string | null;
  n: Int8 | null;
  status: string | null;
}

export interface VOverrideRate {
  approved_like: Int8 | null;
  classification_category: string | null;
  disposed: Int8 | null;
  draft_source: string | null;
  edit_reject_rate: Numeric | null;
  edited: Int8 | null;
  rejected: Int8 | null;
}

export interface DB {
  classification_log: ClassificationLog;
  draft_feedback: DraftFeedback;
  drafts: Drafts;
  inbox_messages: InboxMessages;
  kb_documents: KbDocuments;
  migrations: Migrations;
  onboarding: Onboarding;
  persona: Persona;
  rejected_history: RejectedHistory;
  sent_history: SentHistory;
  state_transitions: StateTransitions;
  system_state: SystemState;
  v_drafting_metrics: VDraftingMetrics;
  v_override_rate: VOverrideRate;
}
