-- Migration 049 — Spec 002 FR7 (Stage 2b-1): the Train sender-rules table.
-- WHAT: New mailbox.sender_rules table. One row per operator "Train" rule that
--       maps a sender (exact email OR whole domain) to a target bucket, in one
--       of two modes:
--         - 'bias'  (DEFAULT, the safe path): a strong PRIOR the classifier
--                    still reconciles — feeds a prompt hint, content can override.
--                    Use for MULTI-INTENT senders (clients, colleagues, Reverb).
--         - 'force' (narrow, opt-in): a hard pre-LLM route, allowed ONLY for
--                    single-purpose automated senders that emit exactly one type
--                    (gemini-notes→meeting_notes, Gusto payroll→notification, …).
--       Mirrors mailbox.vip_senders (migration 028): kind IN ('email','domain'),
--       match stored lowercased, unique within (account_id, match, kind).
-- WHY:  Spec 002 FR7 "Train mechanics — sender-rules + few-shot". This is the
--       MBOX-370 / MBOX-368 fix: the reverted force-to-category override
--       (migration 041, reverted 043) mis-filed multi-intent senders' other mail.
--       The force/bias split keeps force narrow (single-purpose automated senders)
--       and makes bias the default — a prior the model reconciles, never a bypass.
--       Apply lib is lib/classification/sender-rules.ts (the sender_never_spam
--       safety envelope: account-scoped, fail-open, kill switch SENDER_RULES_DISABLE=1).
-- ADDITIVE + REVERSIBLE: new table only, no DML, no change to existing tables.
--       target_bucket CHECK is the SAME 23-value union as migration 048's category
--       CHECK and lib/classification/prompt.ts CATEGORIES — kept in lockstep by
--       test/sender-rules-migration.test.ts.
-- ROLLBACK (no down-runner — manual, per migration 046/047/048 style):
--   DROP TABLE IF EXISTS mailbox.sender_rules;
--   then revert lib/classification/sender-rules.ts, lib/queries-sender-rules.ts,
--   scripts/seed-sender-rules.ts, the classify-one/classify-sweeper/prompt wiring,
--   and lib/db/schema.ts (regenerated by `npm run db:codegen`). Self-contained —
--   no data carried elsewhere.

CREATE TABLE IF NOT EXISTS mailbox.sender_rules (
  id             SERIAL PRIMARY KEY,
  -- Account scope. Every sibling Train/classify table is account-scoped
  -- (migration 033). NOT NULL with no DEFAULT — the write path always resolves
  -- it via getDefaultAccountId() and passes it explicitly, so a rule can never
  -- silently mis-file to account 1 (the exact bug 2a's account_id tagging fixed).
  account_id     INTEGER NOT NULL,
  -- The matchable value. For kind='email' this is a full address
  -- (e.g. 'gemini-notes@google.com'); for kind='domain' it is a bare domain
  -- (e.g. 'e.fender.com'). Stored lowercased by the write path (same
  -- extractAddress normalization the allowlist uses) so the classify-time lookup
  -- is a case-sensitive equality compare. "match" is quoted because MATCH is a
  -- SQL keyword; the column name is lowercase `match`.
  "match"        TEXT NOT NULL,
  -- Closed enum, kept in lockstep with SENDER_RULE_KINDS in
  -- lib/classification/sender-rules.ts. exact-email or domain — NO regex.
  kind           TEXT NOT NULL,
  -- The bucket this sender maps to. CHECK is the SAME 23-value union as
  -- migration 048's category CHECK + prompt.ts CATEGORIES (lockstep gate:
  -- test/sender-rules-migration.test.ts).
  target_bucket  TEXT NOT NULL,
  -- 'force' = hard pre-LLM route (single-purpose senders only).
  -- 'bias'  = a prior the classifier reconciles (DEFAULT, the safe path).
  mode           TEXT NOT NULL DEFAULT 'bias',
  -- Per-rule reversibility: disable a rule without deleting the audit row.
  enabled        BOOLEAN NOT NULL DEFAULT TRUE,
  -- Operator audit columns.
  reason         TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by     TEXT,

  CONSTRAINT sender_rules_kind_check CHECK (kind IN ('email', 'domain')),
  CONSTRAINT sender_rules_mode_check CHECK (mode IN ('force', 'bias')),
  CONSTRAINT sender_rules_match_not_blank CHECK (length(trim("match")) > 0),
  CONSTRAINT sender_rules_target_bucket_check CHECK (target_bucket = ANY (ARRAY[
    'inquiry','reorder','scheduling','follow_up','internal','spam_marketing','escalate','unknown',
    'client_request','proposal_request','sales_lead','meeting_invite','meeting_notes',
    'receipt','marketplace_notification','marketing_promo','vendor_partner','finance_legal',
    'admin_account','invoice_payable','contract_legal','notification','spam'
  ]))
);

-- One row per (account_id, match, kind) — re-adding the same rule is an
-- idempotent upsert, not a duplicate. An email and a domain that share a string
-- are distinct rows (different kind), so kind is part of the key.
CREATE UNIQUE INDEX IF NOT EXISTS sender_rules_account_match_kind_uidx
  ON mailbox.sender_rules(account_id, "match", kind);

-- Read pattern: the classify-time lookup filters by account_id + enabled + match.
-- A partial index on the enabled rows keeps the per-message lookup cheap.
CREATE INDEX IF NOT EXISTS sender_rules_account_enabled_idx
  ON mailbox.sender_rules(account_id) WHERE enabled;
