-- Migration 050 — Spec 002 FR7b (Stage 2b-2): the classifier few-shot exemplars table.
-- WHAT: New mailbox.classification_exemplars table. One row per labeled
--       (snippet → bucket) example the classifier prompt can inject as a
--       few-shot demonstration so lookalike mail from NEW senders is nudged into
--       the right bucket. This is what the Spec 003 "Train" UI writes to when
--       the operator corrects a message (the corrected message becomes an exemplar via
--       source_msg_id). Mirrors the drafting exemplar surface
--       (lib/drafting/exemplars.ts + persona.category_exemplars + drafts.exemplar_refs)
--       rather than inventing a new mechanism (plan §2b "mirror drafting exemplars").
-- WHY:  Spec 002 FR7 "(b) Few-shot exemplars — labeled (snippet → bucket) examples
--       injected into the classifier prompt". Sender rules (migration 049) fix the
--       deterministic senders; few-shot teaches the model the fuzzy/lookalike cases
--       a single sender rule can't (FR7 open question: cap + retrieve most-relevant
--       K, never dump all — protected at the injection layer, not here).
-- ADDITIVE + REVERSIBLE: new table only, no DML, no change to existing tables.
--       bucket CHECK is the SAME 23-value union as migration 048's category CHECK +
--       migration 049's target_bucket CHECK + lib/classification/prompt.ts CATEGORIES —
--       kept in lockstep by test/classification-exemplars-migration.test.ts.
-- ROLLBACK (no down-runner — manual, per migration 046/047/048/049 style):
--   DROP TABLE IF EXISTS mailbox.classification_exemplars;
--   then revert lib/queries-classification-exemplars.ts, lib/classification/exemplars.ts,
--   the buildPrompt/classify-one/classify-sweeper few-shot wiring, and lib/db/schema.ts
--   (regenerated by `npm run db:codegen`). Self-contained — no data carried elsewhere.

CREATE TABLE IF NOT EXISTS mailbox.classification_exemplars (
  id             SERIAL PRIMARY KEY,
  -- Account scope. Every sibling Train/classify table is account-scoped
  -- (migration 033). NOT NULL with no DEFAULT — the write path always resolves
  -- it via getDefaultAccountId() and passes it explicitly so an exemplar can
  -- never silently leak across mailboxes (the bug 2a's account_id tagging fixed).
  account_id     INTEGER NOT NULL,
  -- The labeled example text: subject + a body excerpt, capped by the write path
  -- (mirrors lib/drafting/exemplars.ts RAG_RETRIEVE_EXCERPT_CHARS). This is the
  -- "snippet" the prompt renders as a (snippet → bucket) demonstration.
  snippet        TEXT NOT NULL,
  -- The bucket this exemplar demonstrates. CHECK is the SAME 23-value union as
  -- migrations 048/049 + prompt.ts CATEGORIES (lockstep gate:
  -- test/classification-exemplars-migration.test.ts).
  bucket         TEXT NOT NULL,
  -- Optional company/sender label (spec entity "company (optional)") — display
  -- + future per-company retrieval bias; not required by the injection path.
  company        TEXT,
  -- The mailbox.inbox_messages / classification message id this exemplar was
  -- minted FROM (a Train correction). Nullable: hand-authored exemplars have none.
  source_msg_id  TEXT,
  -- Per-exemplar reversibility: disable without deleting the audit row. The
  -- retrieval path ignores disabled rows.
  enabled        BOOLEAN NOT NULL DEFAULT TRUE,
  -- Operator audit columns.
  reason         TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by     TEXT,

  CONSTRAINT classification_exemplars_snippet_not_blank CHECK (length(trim(snippet)) > 0),
  CONSTRAINT classification_exemplars_bucket_check CHECK (bucket = ANY (ARRAY[
    'inquiry','reorder','scheduling','follow_up','internal','spam_marketing','escalate','unknown',
    'client_request','proposal_request','sales_lead','meeting_invite','meeting_notes',
    'receipt','marketplace_notification','marketing_promo','vendor_partner','finance_legal',
    'admin_account','invoice_payable','contract_legal','notification','spam'
  ]))
);

-- One exemplar per corrected message: re-correcting the same message is an
-- idempotent upsert, not a duplicate (partial — hand-authored null-source rows
-- are exempt and may repeat). Matches the upsert in
-- lib/queries-classification-exemplars.ts:upsertClassificationExemplar.
CREATE UNIQUE INDEX IF NOT EXISTS classification_exemplars_account_source_uidx
  ON mailbox.classification_exemplars(account_id, source_msg_id)
  WHERE source_msg_id IS NOT NULL;

-- Read pattern: retrieval lists the most-recent enabled exemplars for an
-- account, optionally biased toward one bucket. Index by (account_id, bucket)
-- over the enabled rows keeps the per-classify lookup cheap.
CREATE INDEX IF NOT EXISTS classification_exemplars_account_bucket_idx
  ON mailbox.classification_exemplars(account_id, bucket) WHERE enabled;
